# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 89478281e791baa225fb672a5b9fa850525215e1d61d6d32a964a1efae93f6fedd47461bf30783929c36c9b4dac8eb910c5357aa8b156500acd4acf86349ce95

test:
  secret_key_base: 15da77cfc03f176635f19b4065dee1b0ce929b2f25ac19949e0e3a46e2d0b368a84ad8b4da1b9a5f3f19fb9b49dd03c220ca32e18d7084ed1533a089b6fa0a35

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
